version: "3.8"
services:

  mysql:
    image: mysql/mysql-server:5.7
    container_name: mysqllab3
    restart: always
    ports:
      - "33060:3306"
    command: mysqld 
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=demo
      - MYSQL_DATABASE=demo
      - MYSQL_PASSWORD=demo


  maven-app:
    container_name: quotesapi
    image: maven-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 8080:8080
    depends_on:
      - "mysql"
    command: [ "./mvnw", "spring-boot:run" ]
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/demo
      - spring.datasource.username=demo
      - spring.datasource.password=demo
      - spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect
      - spring.jpa.hibernate.ddl-auto=update